Del_Sys/Del_Sys/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from main import views

from main.customer import views as customer_views
from main.courier import views as courier_views,apis as courier_apis

customer_urlpatterns=[
    path('',customer_views.home, name='home'),
    path('profile/',customer_views.profile_page,name="profile"),
    path('payment_method/',customer_views.payment_method_page,name="payment_method"),
    path('create_job/',customer_views.create_job_page,name="create_job"),

    path('jobs/current/',customer_views.current_jobs_page,name="current_jobs"),
    path('jobs/archived/',customer_views.archived_jobs_page,name="archived_jobs"),
    path('jobs/<job_id>/',customer_views.job_page,name="job"),
    
]

courier_urlpatterns=[
    path('',courier_views.home, name="home"),
    path('jobs/available/',courier_views.available_jobs_page, name="available_jobs"),
    path('jobs/available/<id>/',courier_views.available_job_page, name="available_job"),
    path('jobs/current/',courier_views.current_job_page, name="current_job"),
    path('jobs/current/<id>/take_photo/',courier_views.current_job_take_photo_page, name="current_job_take_photo"),
    path('jobs/complete/',courier_views.job_complete_page, name="job_complete"),
    path('jobs/archived/',courier_views.archived_jobs_page, name="archived_jobs"),
    path('profile/',courier_views.profile_page, name="profile"),


    path('api/jobs/available/',courier_apis.available_jobs_api, name="available_jobs_api"),
    path('api/jobs/current/<id>/update/',courier_apis.current_job_update_api, name="current_job_update_api"),
]


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),


    path('sign_in/', auth_views.LoginView.as_view(template_name="sign_in.html"), name='sign_in'),

    path('sign_out/', auth_views.LogoutView.as_view(next_page="/"), name='sign_out'),
    path('sign_up/', views.sign_up, name='sign_up'),
    
    path('customer/', include((customer_urlpatterns,'customer'))),
    path('courier/',  include((courier_urlpatterns,'courier'))),


    # Include allauth URLs for authentication
    path('accounts/', include('allauth.urls')),


    # URL pattern for Google login
    path('login/google/', views.google_login, name='google_login'),

    path('login/google/callback/', views.google_callback, name='google_callback'),


    # path('', include('social_django.urls')),


    # Include social authentication URLs

    path('', include('social_django.urls', namespace='social')),    

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Del_Sys/main/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils import timezone

# Create your models here.

class Customer(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    avatar=models.ImageField(upload_to='customer/avatars/', blank=True, null=False)
    phone_number=models.CharField(max_length=50,blank=True)
    stripe_customer_id=models.CharField(max_length=255, blank=True)
    stripe_payment_method_id=models.CharField(max_length=255, blank=True)
    stripe_card_last4 =models.CharField(max_length=255, blank=True)


    def __str__(self):
        return self.user.get_full_name()


class Courier(models.Model):
    user= models.OneToOneField(User, on_delete=models.CASCADE)
    lat= models.FloatField(default=0)
    lng= models.FloatField(default=0)
    
    def __str__(self):
        return self.user.get_full_name()



class Category(models.Model):
    slug=models.CharField(max_length=255, unique=True)
    name=models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Job(models.Model):
    SMALL_SIZE="small"
    MEDIUM_SIZE="medium"
    LARGE_SIZE="large"
    SIZES=(
        (SMALL_SIZE,'Small'),
        (MEDIUM_SIZE,'Medium'),
        (LARGE_SIZE,'Large'),
    )

    CREATING_STATUS='creating'
    PROCESSING_STATUS='processing'
    PICKING_STATUS='picking'
    DELIVERING_STATUS='delivering'
    COMPLETED_STATUS='completing'
    CANCELED_STATUS='cancelled'
    STATUSES=(
        (CREATING_STATUS,'Creating'),
        (PROCESSING_STATUS,'Processing'),
        (PICKING_STATUS,'Picking'),
        (DELIVERING_STATUS,'Delivering'),
        (COMPLETED_STATUS,'Completed'),
        (CANCELED_STATUS,'Cancelled'),
    )


    # Step 1
    id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    customer=models.ForeignKey(Customer, on_delete=models.CASCADE)
    courier=models.ForeignKey(Courier, on_delete=models.CASCADE, null=True, blank=True)
    name=models.CharField(max_length=255)
    description= models.CharField(max_length=255)
    category=models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    size=models.CharField(max_length=20, choices=SIZES, default=MEDIUM_SIZE)
    quantity=models.IntegerField(default=1)
    photo= models.ImageField(upload_to='job/photos/')
    status=models.CharField(max_length=20, choices=STATUSES, default=CREATING_STATUS)
    created_at=models.DateTimeField(default=timezone.now)


    #Step 2
    pickup_address=models.CharField(max_length=255, blank=True)
    pickup_lat=models.FloatField(default=0)
    pickup_lng=models.FloatField(default=0)
    pickup_name=models.CharField(max_length=255, blank=True)
    pickup_phone=models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.description


    #Step 3
    delivery_address=models.CharField(max_length=255, blank=True)
    delivery_lat=models.FloatField(default=0)
    delivery_lng=models.FloatField(default=0)
    delivery_name=models.CharField(max_length=255, blank=True)
    delivery_phone=models.CharField(max_length=255, blank=True)

    #Step 4
    duration=models.IntegerField(default=0)
    distance=models.FloatField(default=0)
    price=models.FloatField(default=0)

    #Extra Info
    pickup_photo=models.ImageField(upload_to='job/pickup_photos/', null=True, blank=True)
    pickedup_at=models.DateTimeField(null=True, blank=True)

    delivery_photo=models.ImageField(upload_to='job/delivery_photos/', null=True, blank=True)
    delivered_at=models.DateTimeField(null=True, blank=True)


    def __str__(self):
        return self.description

class Transaction(models.Model):
    stripe_payment_intent_id=models.CharField(max_length=255, unique=True)
    job=models.ForeignKey(Job, on_delete=models.CASCADE)
    amount=models.FloatField(default=0)
    created_at=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.stripe_payment_intent_id

Del_Sys/main/customer/forms.py
from django import forms
from django.contrib.auth.models import User
from main.models import Customer,Job

class BasicUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('first_name','last_name')


class BasicCustomerForm(forms.ModelForm):
    class Meta:
        model=Customer
        fields=('avatar',)

class JobCreateStep1Form(forms.ModelForm):
    class Meta:
        model= Job
        fields=('name','description', 'category', 'size', 'quantity', 'photo')


class JobCreateStep2Form(forms.ModelForm):
    pickup_address=forms.CharField(required=True)
    pickup_name=forms.CharField(required=True)
    pickup_phone=forms.CharField(required=True)
    class Meta:
        model= Job
        fields=('pickup_address','pickup_lat','pickup_lng','pickup_name','pickup_phone')

class JobCreateStep3Form(forms.ModelForm):
    delivery_address=forms.CharField(required=True)
    delivery_name=forms.CharField(required=True)
    delivery_phone=forms.CharField(required=True)
    class Meta:
        model= Job
        fields=('delivery_address','delivery_lat','delivery_lng','delivery_name','delivery_phone')

Del_Sys/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=250)
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        if User.objects.filter(email=email).exists():
            raise ValidationError("This email is already taken.")
        return email

Del_Sys/main/courier/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from main.models import *

# Create your views here.


@login_required(login_url="/sign_in/?next=/courier/")
def home(request):
    return redirect(reverse('courier:available_jobs'))


@login_required(login_url="/sign_in/?next=/courier/")
def available_jobs_page(request):
    return render(request,'courier/available_jobs.html')


@login_required(login_url="/sign_in/?next=/courier/")
def available_job_page(request, id):
    job = Job.objects.filter(id=id, status=Job.PROCESSING_STATUS).last()

    if not job:
        return redirect(reverse('courier:available_jobs'))

    if request.method=='POST':
        job.courier=request.user.courier
        job.status = Job.PICKING_STATUS
        job.save()

        return redirect(reverse('courier:available_jobs'))

    return render(request,'courier/available_job.html', {
        "job": job
    })

    
@login_required(login_url="/sign_in/?next=/courier/")
def current_job_page(request):
    job = Job.objects.filter(
        courier=request.user.courier,
        status__in=[
            Job.PICKING_STATUS,
            Job.DELIVERING_STATUS
        ]
    ).last()

    return render(request, 'courier/current_job.html',{
        "job":job
    })


@login_required(login_url="/sign_in/?next=/courier/")
def current_job_take_photo_page(request,id):
    job=Job.objects.filter(
        id=id,
        courier=request.user.courier,
        status__in=[
            Job.PICKING_STATUS,
            Job.DELIVERING_STATUS
        ]
    ).last()

    if not job:
        return redirect(reverse('courier:current_job'))

    return render(request, 'courier/current_job_take_photo.html',{
        "job": job
    })



@login_required(login_url="/sign_in/?next=/courier/")
def job_complete_page(request):
    return render(request,'courier/job_complete.html')


@login_required(login_url="/sign_in/?next=/courier/")
def archived_jobs_page(request):
    jobs= Job.objects.filter(
        courier=request.user.courier,
        status=Job.COMPLETED_STATUS
    )
    return render(request,'courier/archived_jobs.html',{
        "jobs":jobs
    })


@login_required(login_url="/sign_in/?next=/courier/")
def profile_page(request):
    jobs= Job.objects.filter(
        courier=request.user.courier,
        status=Job.COMPLETED_STATUS
    )

    total_earnings=round(sum(job.price for job in jobs) * 0.8, 2)
    total_jobs= len(jobs)
    total_km = sum(job.distance for job in jobs)

    return render(request,'courier/profile.html',{
        "total_earnings":total_earnings,
        "total_jobs":total_jobs,
        "total_km":total_km,
    })

Del_Sys/main/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from allauth.socialaccount.models import SocialAccount
from django.urls import reverse
from django.contrib import messages
from . import forms

# Create your views here.

def home(request):
    return render(request,"home.html")

def sign_up(request):
    form=forms.SignUpForm()

    if request.method=='POST':
        form=forms.SignUpForm(request.POST)

        if form.is_valid():
            email=form.cleaned_data.get('email').lower()
            user=form.save(commit=False)
            user.username=email
            user.save()         

            login(request,user,backend='django.contrib.auth.backends.ModelBackend')
            return redirect('/')

    return render(request,"sign_up.html",
        {
            'form':form
        }
    )

def google_login(request):
    # Redirect the user to Google authentication URL
    return redirect(reverse('social:begin', args=['google']))


def google_callback(request):
    messages.success(request, 'Successfully logged in with Google.')
    return redirect('/')

# def google_login(request):
#     return redirect('sign_in', 'google')

# def google_callback(request):
#     # Get the user from the social account
#     social_account = SocialAccount.objects.filter(provider='google', user=request.user).first()
#     if social_account:
#         # If the social account exists, log in the user
#         login(request, social_account.user)
#         return redirect('/')  # Redirect to home page or any other desired URL
#     else:
#         return redirect('/sign_in/')  # Redirect to sign-in page if the social account does not exist

Del_Sys/main/templates/customer/base.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% url 'customer:create_job' as create_job_url %}
{% url 'customer:profile' as profile_url  %}
{% url 'customer:current_jobs' as current_jobs_url  %}
{% url 'customer:archived_jobs' as archived_jobs_url  %}
{% url 'customer:payment_method' as payment_method_url  %}





<div class="container bg-light mt-4 pt-3 pb-3">
    <div class="row">
        <div class="col-lg-4">
            <div class="text-center">
                <img src="{% if request.user.customer.avatar %}{{ request.user.customer.avatar.url }} {% else %} {% static 'img/avatar.png' %} {% endif %} " alt="" class="rounded-circle mb-2" width="100" height="100">
                <h4>
                    {{ request.user.get_full_name }}
                </h4>
                <p class="text-secondary">{{ request.user.email }}</p>
            </div>

            <div class="list-group mt-5">
                <a href="{% url 'customer:create_job'  %}" class="list-group-item list-group-item-action {% if request.path == create_job_url %}active{% endif %}"> 
                  Create an Order
                </a>

                <a href="{% url 'customer:current_jobs' %}" class="list-group-item list-group-item-action {% if request.path == current_jobs_url or request.path == archived_jobs_url %}active{% endif %} "> 
                  My Order
                </a>

                <a href="{% url 'customer:profile'  %}" class="list-group-item list-group-item-action {% if request.path == profile_url %}active{% endif %}"> 
                  Profile Information
                </a>

                <a href="{% url 'customer:payment_method'  %}" class="list-group-item list-group-item-action  {% if request.path == payment_method_url %}active{% endif %}"> 
                  Payment Details
                </a>

            </div>

        </div>

        <div class="col-lg-8">
            {% block main %}
            {% endblock %}
        </div>
    </div>
</div>

<!-- Include Bootoast library -->
<script src="https://unpkg.com/bootoast@1.0.1/dist/bootoast.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/bootoast@1.0.1/dist/bootoast.min.css">

<!-- JavaScript for displaying messages -->
<script>
    function toast(message, type) {
      bootoast.toast({
        position: 'leftBottom',
        message: message,
        type: type,
      });
    }
  
    {% if messages %}
      {% for message in messages %}
        toast('{{ message }}', '{{ message.tags }}');
      {% endfor %}
    {% endif %}
  </script>
{% endblock %}

Del_Sys/main/templates/customer/job.html
{% extends 'customer/base.html' %}
{% load static %}
{% block head %}

<style>
    .photo {
        object-fit: cover;
    }

    .photo-blank {
        border: 2px dashed #dfdfdf;
        height: 130px;
        width: 130px;
        border-radius: 5px;
        align-items: center;
        display: flex;
        justify-content: center;
        text-align: center;
        padding: 10px;
    }
</style>
{% endblock %}

{% block main %}
<!-- JOB DESCRIPTION -->
<div class="media mb-4">
    <img src="{{ job.photo.url }}" class="rounded-lg mr-3" width="150" height="150">
    <div class="media-body">

        {% if job.status == 'processing' %}
        <form  method="POST" class="float-right">
            {% csrf_token %}
            <button type="submit" class="btn btn-warning"> Cancel Job</button>
        </form>
        {% endif %}




        <h4>{{ job.name }}</h4>
        <p class="text-secondary">{{ job.description }}</p>
        <div class="row">
            <div class="col-lg-3">
                <small class="text-secondary"> CATEGORY </small><br>
                <span><b>{{ job.category.name }}</b></span>
            </div>
            <div class="col-lg-3">
                <small class="text-secondary"> SIZE </small><br>
                <span><b>{{ job.get_size_display }}</b></span>
            </div>
            <div class="col-lg-3">
                <small class="text-secondary"> PRICE </small><br>
                <span><b>रु {{ job.price }}</b></span>
            </div>
            <div class="col-lg-3">
                <small class="text-secondary"> QUANTITY </small><br>
                <span><b>{{ job.quantity }}</b></span>
            </div>
        </div>
    </div>
</div>

<!-- DELIVERY INFORMATION -->
<b class="text-secondary">DELIVERY INFORMATION</b>
<div class="card bg-white mt-2 mb-5">
    <div class="card-body p-4">
        <h4 class="mb-3">
            Pickup
        </h4>
        <div class="row">
            <div class="col-lg-4">
                <b>Address</b><br>
                <span>{{ job.pickup_address }}</span>
            </div>
            <div class="col-lg-4">
                <b>{{ job.pickup_name }}</b><br>
                <span>{{ job.pickup_phone }}</span>
            </div>
            <div id="pickup_photo" class="col-lg-4">
                {% if job.pickup_photo %}
                <img src="{{ job.pickup_photo.url }}" class="rounded-lg photo" width="130" height="130">
                {% else %}
                <div class="photo-blank">Pickup photo will appear here</div>
                {% endif %}
            </div>
        </div>
        <hr class="my-4">
        <h4 class="mb-3">
            Delivery
        </h4>
        <div class="row">
            <div class="col-lg-4">
                <b>Address</b><br>
                <span>{{ job.delivery_address }}</span>
            </div>
            <div class="col-lg-4">
                <b>{{ job.delivery_name }}</b><br>
                <span>{{ job.delivery_phone }}</span>
            </div>
            <div id="pickup_photo" class="col-lg-4">
                {% if job.delivery_photo %}
                <img src="{{ job.delivery_photo.url }}" class="rounded-lg photo" width="130" height="130">
                {% else %}
                <div class="photo-blank">Delivery photo will appear here</div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- MAP AREA -->
<div class="d-flex justify-content-between">
    <b class="text-secondary">TRACK DELIVERY</b>
    <div>
        <span class="badge badge-warning"> {{ job.get_status_display }}</span>
    </div>
</div>
<div class="card bg-white mt-2">
    <div class="card-body p-0">
        <div id="map" style="height: 500px;"></div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-routing-machine/3.3.4/leaflet-routing-machine.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet-routing-machine/3.2.12/leaflet-routing-machine.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-routing-machine/3.2.12/leaflet-routing-machine.min.js"></script>

<script>
    $(document).ready(function() {
        // Extract pickup and delivery coordinates from the job object
        var pickupCoords = [{{ job.pickup_lat }}, {{ job.pickup_lng }}];
        var deliveryCoords = [{{ job.delivery_lat }}, {{ job.delivery_lng }}];

        function displayTracedRouteMap(pickupCoords, deliveryCoords) {
            var map = L.map('map');
            
            // Create an array of marker positions
            var markerPositions = [pickupCoords, deliveryCoords];

            // Calculate the bounds based on marker positions
            var bounds = L.latLngBounds(markerPositions);

            // Set the map view to fit the bounds
            map.fitBounds(bounds);

            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            }).addTo(map);

            // Custom icon URLs
            var pickupIconUrl = "{% static 'img/pickup.png' %}";
            var deliveryIconUrl = "{% static 'img/delivery.png' %}";

            // Define custom icons
            var pickupIcon = L.icon({
                iconUrl: pickupIconUrl,
                iconSize: [32, 32], // adjust as needed
                iconAnchor: [16, 32], // point of the icon which will correspond to marker's location
                popupAnchor: [0, -32] // point from which the popup should open relative to the iconAnchor
            });

            var deliveryIcon = L.icon({
                iconUrl: deliveryIconUrl,
                iconSize: [32, 32], // adjust as needed
                iconAnchor: [16, 32], // point of the icon which will correspond to marker's location
                popupAnchor: [0, -32] // point from which the popup should open relative to the iconAnchor
            });

            // Add marker for pickup location with custom icon
            L.marker(pickupCoords, { icon: pickupIcon }).addTo(map)
                .bindPopup('Pickup Location')
                .openPopup();

            // Add marker for delivery location with custom icon
            L.marker(deliveryCoords, { icon: deliveryIcon }).addTo(map)
                .bindPopup('Delivery Location')
                .openPopup();

            // Create routing control and add it to the map

        }

        // Call the function to display the traced route map
        displayTracedRouteMap(pickupCoords, deliveryCoords);
    });
</script>

{% endblock %}

<!-- for commit -->

Del_Sys/main/templates/customer/jobs.html
{% extends 'customer/base.html' %}

{% block main %}

{% url 'customer:current_jobs' as current_jobs_url %}
{% url 'customer:archived_jobs' as archived_jobs_url %}


<!-- TABS -->
<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
      <a class="nav-link {% if request.path == current_jobs_url %}active{% endif %} " href="{% url 'customer:current_jobs' %}">Current Jobs</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if request.path == archived_jobs_url %}active{% endif %}" href="{% url 'customer:archived_jobs' %}">Archived Jobs</a>
    </li>
</ul>

<!-- LIST OF JOBS -->
<div class="list-group mt-3">
    {% if jobs %}
        {% for job in jobs %}
            <a href="{% url 'customer:job' job.id %}" class="list-group-item list-group-item-action">
                <div class="media">
                    <img src="{{ job.photo.url }}" class="rounded-lg mr-3" width="100" height="100">
                    <div class="media-body">
                        <div class="row">
                            <div class="col-lg-8">
                                <h5 class="mb-1">{{ job.name }}</h5>
                                <p>{{ job.description }}</p>

                                <div class="d-flex mb-4">
                                    <i class="fas fa-map-marker-alt"></i>
                                    <div class="ml-2">
                                        <b>{{ job.pickup_name }}</b><br>
                                        <small>{{ job.pickup_address }}</small>
                                    </div>
                                </div>
                                
                                <div class="d-flex">
                                    <i class="fas fa-flag-checkered"></i>
                                    <div class="ml-2">
                                        <b>{{ job.delivery_name }}</b><br>
                                        <small>{{ job.delivery_address }}</small>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-4 text-right d-flex flex-column justify-content-between">
                                <div><span class="badge badge-warning mb-2">{{ job.get_status_display }}</span></div>
                                <h2 class="mb-1">रु {{ job.price }}</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        {% endfor %}
    {% else %}
        <div class="card">
            <div class="card-body text-center">
                Nothing to show here
            </div>
        </div>
    {% endif %}
</div>


{% endblock %}

Del_Sys/main/templates/customer/payment_method.html
{% extends 'customer/base.html' %}
{% load bootstrap4 %}

{% block head %}
<script src="https://js.stripe.com/v3/"></script>

<style>
    .StripeElement {
        height: 40px;
        padding: 10px 12px;
        width: 100%;
        color: #32325d;
        background-color: white;
        border: 1px solid #ced4da;
        border-radius: 4px;
    }

    .StripeElement--focus {
        border-color: #80bdff;
        box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, .25);
    }

    .StripeElement--invalid {
        border-color: #fa755a;
    }

    .StripeElement--webkit-autofill {
        background-color: #fefde5 !important;
    }
</style>

{% endblock %}

{% block main %}




{% if not request.user.customer.stripe_payment_method_id %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    Let's add your Credit or Debit Card to <strong>Create a Job</strong>!
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

{% endif %}

<b class="text-secondary"> Your Credit/Debit Card</b>

<div class="card bg-white mt-2 mb-5">
    <div class="card-body">

        {% if request.user.customer.stripe_payment_method_id %}
        <div id="change-card" class="input-group">
            <input type="text" class="form-control" disabled value="**** **** **** {{ request.user.customer.stripe_card_last4 }}">
            <div class="input-group-append">
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Remove</button>
                </form>
            </div>
        </div>

        {% else %}


        <form id="setup-form" data-secret="{{ client_secret }}">
            <div id="card-element"></div>
            <button id="card-button" class="btn btn-warning mt-3" type="button">Save Card</button>
        </form>
        {% endif %}

    </div>
</div>


{% if not request.user.customer.stripe_payment_method_id %}
<script>
    var stripe = Stripe("{{ STRIPE_API_PUBLIC_KEY }}");
    var elements = stripe.elements();
    var cardElement = elements.create('card');
    cardElement.mount('#card-element');

    var cardButton = document.getElementById('card-button');
    var clientSecret = "{{ client_secret }}";

    cardButton.addEventListener('click', function(ev) {
        stripe.confirmCardSetup(
            clientSecret, {
                payment_method: {
                    card: cardElement,
                },
            }
        ).then(function(result) {
            if (result.error) {
                // Display error.msg
                toast(result.error.message,'error');
            } else {
                toast("Payment method is added",'success');
                window.location.reload();
            }
        });
    });

        // Add event listener for removing card
    document.getElementById('remove-card-form').addEventListener('submit', function(event) {
        event.preventDefault();
            var form = this;
            if (confirm("Are you sure you want to remove the card?")) {
                // Perform form submission if user confirms
                form.submit();
            }
        });
</script>
{% endif %}
{% endblock %}